"""Add chunks_with_annotations table

Revision ID: 32549047c317
Revises: 4069f15296ff
Create Date: 2024-12-12 13:53:13.363681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid

# revision identifiers, used by Alembic.
revision: str = "32549047c317"
down_revision: Union[str, None] = "4069f15296ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.create_table(
        "chunks_with_annotations",
        sa.Column("article_id", sa.String(), nullable=False),
        sa.Column(
            "chunk_id", sa.UUID(), nullable=False, default=uuid.uuid4, primary_key=True
        ),
        sa.Column("chunk_sequence", sa.String(), nullable=False),
        sa.Column("chunk_name", sa.String(), nullable=False),
        sa.Column("chunk_length", sa.Integer(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("chunk_annotations_count", sa.Integer(), nullable=False),
        sa.Column("chunk_annotations_ids", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("genes", sa.String(), nullable=False),
        sa.Column("species", sa.String(), nullable=False),
        sa.Column("cell_lines", sa.String(), nullable=False),
        sa.Column("strains", sa.String(), nullable=False),
        sa.Column("diseases", sa.String(), nullable=False),
        sa.Column("chemicals", sa.String(), nullable=False),
        sa.Column("variants", sa.String(), nullable=False),
        sa.Column("chunk_offset", sa.Integer(), nullable=False),
        sa.Column("chunk_infons", sa.JSON(), nullable=False),
        sa.Column("chunker_type", sa.String(), nullable=False),
        sa.Column("merger_type", sa.String(), nullable=False),
        sa.Column("aioner_model", sa.String(), nullable=False),
        sa.Column("gnorm2_model", sa.String(), nullable=False),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chunks_blk",
        sa.Column("chunk_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("chunk_sequence", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("chunk_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("chunk_length", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("token_count", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "chunk_annotations_count", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "chunk_annotations_ids",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "chunk_annotations_types",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("chunk_offset", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "chunk_infons",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("chunker_type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("merger_type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("aioner_model", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("gnorm2_model", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("article_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "chunk_similarity",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_query", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "embed_model", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "annotation_model",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "chunking_strategy",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "annotation_placement_strategy",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "contains_summary",
            sa.VARCHAR(length=3),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "chunk_sequence", sa.VARCHAR(length=10), autoincrement=False, nullable=False
        ),
        sa.Column(
            "similarity_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "chunk_file", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="chunk_similarity_pkey"),
    )
    # ### end Alembic commands ###
